# Generates src/names.h (room / area names) from alttpo's lttp_names.bml
import sys, io
src = sys.argv[1]
dst = sys.argv[2]
uw, ow = {}, {}
cur = None
for line in io.open(src, encoding="utf-8"):
    line = line.rstrip("\n")
    if line.startswith("underworld"):
        cur = uw; continue
    if line.startswith("overworld"):
        cur = ow; continue
    s = line.strip()
    if not s or cur is None or ":" not in s:
        continue
    k, v = s.split(":", 1)
    try:
        cur[int(k.strip(), 16)] = v.strip().encode("ascii", "replace").decode().replace('"', "'").replace("\\", "/")
    except ValueError:
        pass
with io.open(dst, "w", encoding="ascii", newline="\n") as f:
    f.write("// generated by tools/gen_names.py from alttpo's lttp_names.bml\n")
    f.write("typedef struct { uint16_t id; const char *name; } LocName;\n")
    for nm, d in (("kUnderworldNames", uw), ("kOverworldNames", ow)):
        f.write("static const LocName %s[] = {\n" % nm)
        for k in sorted(d):
            f.write('  {0x%04x, "%s"},\n' % (k, d[k]))
        f.write("};\n")
print(len(uw), len(ow))
